# Generated by Django 6.0.2 on 2026-03-06 16:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('color', models.CharField(blank=True, default='primary', help_text='Color for visual identification', max_length=20, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'db_table': 'tables_zone',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('number', models.CharField(max_length=20, verbose_name='Table Number')),
                ('name', models.CharField(blank=True, default='', help_text='Optional friendly name (e.g., "Window Table")', max_length=100, verbose_name='Name')),
                ('capacity', models.PositiveIntegerField(default=4, help_text='Maximum number of guests', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacity')),
                ('position_x', models.PositiveIntegerField(default=0, verbose_name='Position X')),
                ('position_y', models.PositiveIntegerField(default=0, verbose_name='Position Y')),
                ('width', models.PositiveIntegerField(default=10, verbose_name='Width')),
                ('height', models.PositiveIntegerField(default=10, verbose_name='Height')),
                ('shape', models.CharField(choices=[('square', 'Square'), ('round', 'Round'), ('rectangle', 'Rectangle')], default='square', max_length=20, verbose_name='Shape')),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('blocked', 'Blocked')], db_index=True, default='available', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='tables.zone', verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'db_table': 'tables_table',
                'ordering': ['zone__sort_order', 'number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Opened At')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('guests_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Guests')),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('transferred', 'Transferred')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tables.table', verbose_name='Table')),
                ('transferred_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_to', to='tables.tablesession', verbose_name='Transferred From')),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_sessions', to='accounts.localuser', verbose_name='Waiter')),
            ],
            options={
                'verbose_name': 'Table Session',
                'verbose_name_plural': 'Table Sessions',
                'db_table': 'tables_session',
                'ordering': ['-opened_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['hub_id', 'status'], name='tables_sess_hub_id_3cbe4d_idx'), models.Index(fields=['hub_id', 'opened_at'], name='tables_sess_hub_id_df8ad5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['hub_id', 'status'], name='tables_tabl_hub_id_ff7495_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['hub_id', 'is_active'], name='tables_tabl_hub_id_37004c_idx'),
        ),
    ]
